In [1]:


import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('train.csv')
tests = pd.read_csv('test.csv')

In [188]:
data.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,...,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,CommunicationSkill
0,30,0,1,1,2,3,1,3,2,3,...,2564,0,1,14,0,12,2,11,6,4
1,36,0,2,1,12,4,2,3,2,3,...,4663,9,2,12,2,7,2,3,1,2
2,55,1,2,2,2,1,1,3,1,3,...,5160,4,1,16,0,12,3,9,7,5
3,39,0,2,1,24,1,2,1,1,3,...,4108,7,1,13,0,18,2,7,1,4
4,37,0,2,1,3,3,3,3,1,3,...,9434,1,1,15,1,10,2,10,7,1

In [193]:
data.apply('mean')

Age                          35.645577
Attrition                     0.482187
BusinessTravel                2.173833
Department                    1.448403
DistanceFromHome              9.735258
Education                     2.884521
EducationField                2.371007
EnvironmentSatisfaction       2.646192
Gender                        1.388206
JobInvolvement                2.650491
JobRole                       3.836609
JobSatisfaction               2.639435
MaritalStatus                 1.807740
MonthlyIncome              5785.524570
NumCompaniesWorked            2.761671
OverTime                      1.385749
PercentSalaryHike            15.207617
StockOptionLevel              0.692260
TotalWorkingYears             9.949017
TrainingTimesLastYear         2.752457
YearsAtCompany                6.092752
YearsSinceLastPromotion       2.049140
CommunicationSkill            3.135749
dtype: float64

In [196]:
data.apply(max) - data.apply(min)

Age                           42
Attrition                      1
BusinessTravel                 2
Department                     2
DistanceFromHome              28
Education                      4
EducationField                 5
EnvironmentSatisfaction        3
Gender                         1
JobInvolvement                 3
JobRole                        8
JobSatisfaction                3
MaritalStatus                  2
MonthlyIncome              18990
NumCompaniesWorked             9
OverTime                       1
PercentSalaryHike             14
StockOptionLevel               3
TotalWorkingYears             38
TrainingTimesLastYear          6
YearsAtCompany                37
YearsSinceLastPromotion       15
CommunicationSkill             4
dtype: int64

In [200]:
data_norm = (data - data.mean()) / (data.max() - data.min())
data_norm.head()
tests_norm=(tests-tests.mean()) / (tests.max()- tests.min())
tests_norm.head()

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobRole,...,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,CommunicationSkill
0,-0.214539,-0.021277,-0.185106,-0.010486,0.021277,-0.276596,0.430496,-0.408511,0.087943,0.021277,...,-0.239490,-0.185579,-0.280851,0.560790,0.066667,-0.159681,0.048227,-0.051755,-0.150922,0.487234
1,-0.143110,-0.021277,0.314894,-0.117629,0.271277,-0.276596,-0.569504,-0.408511,0.421277,-0.103723,...,-0.059669,0.147754,-0.280851,0.489362,0.400000,0.040319,0.214894,-0.001755,0.182411,-0.012766
2,-0.000253,-0.021277,-0.185106,-0.117629,0.021277,-0.276596,0.097163,-0.408511,0.421277,0.021277,...,-0.032404,0.147754,0.719149,-0.153495,0.400000,0.040319,-0.118440,-0.001755,0.249078,0.237234
3,0.118794,-0.021277,-0.185106,-0.296201,-0.228723,-0.076596,0.430496,0.591489,-0.245390,-0.228723,...,-0.027736,0.703310,0.719149,-0.153495,0.066667,-0.084681,0.214894,-0.076755,-0.150922,0.487234
4,0.190223,-0.521277,-0.185106,-0.189058,-0.228723,-0.076596,0.097163,-0.408511,0.087943,-0.353723,...,-0.113403,-0.185579,-0.280851,-0.224924,-0.266667,-0.059681,0.381560,0.048245,-0.150922,-0.262766

In [3]:
field={'Medical': 1,'Life Sciences': 2,'Other': 3,'Marketing': 4,'Technical Degree': 5,'Human Resources': 6}
travel={'Non-Travel':1, 'Travel_Rarely':2, 'Travel_Frequently':3}
dept={'Research & Development':1, 'Sales':2, 'Human Resources':3}
gender = {'Male': 1,'Female': 2} 
job={'Laboratory Technician':1, 'Manufacturing Director':2,
       'Sales Executive':3, 'Research Scientist':4, 'Sales Representative':5,
       'Healthcare Representative':6, 'Research Director':7,
       'Human Resources':8, 'Manager':9}
overtime = {'No': 1,'Yes': 2} 
marital={'Single':1, 'Married':2, 'Divorced':3}

In [4]:
data.EducationField = [field[item] for item in data.EducationField]
data.BusinessTravel = [travel[item] for item in data.BusinessTravel]
data.Department = [dept[item] for item in data.Department] 
data.OverTime = [overtime[item] for item in data.OverTime]
data.MaritalStatus = [marital[item] for item in data.MaritalStatus]
data.JobRole = [job[item] for item in data.JobRole]
data.Gender = [gender[item] for item in data.Gender]
tests.EducationField = [field[item] for item in tests.EducationField]
tests.BusinessTravel = [travel[item] for item in tests.BusinessTravel]
tests.Department = [dept[item] for item in tests.Department] 
tests.OverTime = [overtime[item] for item in tests.OverTime]
tests.MaritalStatus = [marital[item] for item in tests.MaritalStatus]
tests.JobRole = [job[item] for item in tests.JobRole]
tests.Gender = [gender[item] for item in tests.Gender]

In [5]:
data = data.drop(['Id', 'EmployeeNumber','Behaviour'], axis=1)
tests = tests.drop(['Id', 'EmployeeNumber','Behaviour'], axis=1)

In [254]:
import matplotlib.pyplot as plt
data[data
                    ].hist(figsize=[11,11])

ValueError: Must pass DataFrame with boolean values only

In [201]:
# Create correlation matrix
corr_matrix = data_norm.corr().abs()

# Select upper triangle of correlation matrix
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

# Find features with correlation greater than 0.95
to_drop = [column for column in upper.columns if any(upper[column] > 0.77)]

# Drop features 
data_norm.drop(to_drop, axis=1, inplace=True)
tests_norm.drop(to_drop, axis=1, inplace=True)

In [7]:
tests.columns

Index(['Age', 'BusinessTravel', 'Department', 'DistanceFromHome', 'Education',
       'EducationField', 'EnvironmentSatisfaction', 'Gender', 'JobInvolvement',
       'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'CommunicationSkill'],
      dtype='object')

In [243]:
xtrain = data_norm.drop(['Attrition'],axis=1)
ytrain = data_norm['Attrition']
xtest= tests_norm

In [244]:
data_norm.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'Department', 'DistanceFromHome',
       'Education', 'EducationField', 'EnvironmentSatisfaction', 'Gender',
       'JobInvolvement', 'JobRole', 'JobSatisfaction', 'MaritalStatus',
       'MonthlyIncome', 'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'CommunicationSkill'],
      dtype='object')

In [245]:

tests_norm.columns

Index(['Age', 'BusinessTravel', 'Department', 'DistanceFromHome', 'Education',
       'EducationField', 'EnvironmentSatisfaction', 'Gender', 'JobInvolvement',
       'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'CommunicationSkill'],
      dtype='object')

In [246]:
xtest.columns

Index(['Age', 'BusinessTravel', 'Department', 'DistanceFromHome', 'Education',
       'EducationField', 'EnvironmentSatisfaction', 'Gender', 'JobInvolvement',
       'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'OverTime', 'PercentSalaryHike',
       'StockOptionLevel', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'YearsAtCompany', 'YearsSinceLastPromotion', 'CommunicationSkill'],
      dtype='object')

In [247]:
from sklearn.tree import DecisionTreeClassifier

In [248]:
from sklearn.linear_model import LogisticRegression
LO= LogisticRegression(solver = 'liblinear', penalty='l1', class_weight= {1: 0.4, 0: 0.6}, C=1)
LO.fit(xtrain, ytrain)

ValueError: Unknown label type: 'continuous'

In [249]:
from sklearn.ensemble import RandomForestClassifier

In [250]:
Dt=RandomForestClassifier(n_estimators=100,criterion='entropy',random_state=0)

In [251]:
Dt.fit(xtrain,ytrain)

ValueError: Unknown label type: 'continuous'

In [241]:
ypred=((LO.predict_proba(xtest))+0*(Dt.predict_proba(xtest)))

In [242]:
ypred

array([[0.856376  , 0.143624  ],
       [0.86144324, 0.13855676],
       [0.43166358, 0.56833642],
       [0.40240107, 0.59759893],
       [0.94558768, 0.05441232],
       [0.91295314, 0.08704686],
       [0.51914553, 0.48085447],
       [0.16594465, 0.83405535],
       [0.5306099 , 0.4693901 ],
       [0.84375701, 0.15624299],
       [0.97934087, 0.02065913],
       [0.41542573, 0.58457427],
       [0.8729151 , 0.1270849 ],
       [0.71737141, 0.28262859],
       [0.84384356, 0.15615644],
       [0.67150552, 0.32849448],
       [0.13526219, 0.86473781],
       [0.47906178, 0.52093822],
       [0.82798545, 0.17201455],
       [0.92504475, 0.07495525],
       [0.86699429, 0.13300571],
       [0.03712607, 0.96287393],
       [0.79605372, 0.20394628],
       [0.84276829, 0.15723171],
       [0.39665044, 0.60334956],
       [0.94312109, 0.05687891],
       [0.79472203, 0.20527797],
       [0.90662286, 0.09337714],
       [0.08031886, 0.91968114],
       [0.37724252, 0.62275748],
       [0.92777613, 0.07222387],
       [0.78518369, 0.21481631],
       [0.47446157, 0.52553843],
       [0.36359262, 0.63640738],
       [0.95808153, 0.04191847],
       [0.97162859, 0.02837141],
       [0.91591472, 0.08408528],
       [0.9754946 , 0.0245054 ],
       [0.38659655, 0.61340345],
       [0.14422552, 0.85577448],
       [0.05935268, 0.94064732],
       [0.42634914, 0.57365086],
       [0.93812051, 0.06187949],
       [0.92139441, 0.07860559],
       [0.99526714, 0.00473286],
       [0.79892369, 0.20107631],
       [0.59310653, 0.40689347],
       [0.80379493, 0.19620507],
       [0.98910601, 0.01089399],
       [0.46448453, 0.53551547],
       [0.7043068 , 0.2956932 ],
       [0.62361297, 0.37638703],
       [0.30167903, 0.69832097],
       [0.3800206 , 0.6199794 ],
       [0.39138718, 0.60861282],
       [0.28155972, 0.71844028],
       [0.80482974, 0.19517026],
       [0.0479604 , 0.9520396 ],
       [0.9465824 , 0.0534176 ],
       [0.86813743, 0.13186257],
       [0.899633  , 0.100367  ],
       [0.63882628, 0.36117372],
       [0.26717661, 0.73282339],
       [0.96244933, 0.03755067],
       [0.75325508, 0.24674492],
       [0.8444353 , 0.1555647 ],
       [0.81270256, 0.18729744],
       [0.30879464, 0.69120536],
       [0.60096294, 0.39903706],
       [0.50575832, 0.49424168],
       [0.70601004, 0.29398996],
       [0.73037788, 0.26962212],
       [0.41296945, 0.58703055],
       [0.69181373, 0.30818627],
       [0.25086446, 0.74913554],
       [0.04334226, 0.95665774],
       [0.78150261, 0.21849739],
       [0.64280488, 0.35719512],
       [0.76856315, 0.23143685],
       [0.85222815, 0.14777185],
       [0.83777265, 0.16222735],
       [0.59729262, 0.40270738],
       [0.37553535, 0.62446465],
       [0.99191418, 0.00808582],
       [0.69336781, 0.30663219],
       [0.85130041, 0.14869959],
       [0.37357687, 0.62642313],
       [0.72018047, 0.27981953],
       [0.68443249, 0.31556751],
       [0.87714977, 0.12285023],
       [0.12455299, 0.87544701],
       [0.88586687, 0.11413313],
       [0.62961607, 0.37038393],
       [0.4524256 , 0.5475744 ],
       [0.09080769, 0.90919231],
       [0.22054038, 0.77945962],
       [0.3695234 , 0.6304766 ],
       [0.39112822, 0.60887178],
       [0.9385534 , 0.0614466 ],
       [0.95644378, 0.04355622],
       [0.61396929, 0.38603071],
       [0.90272415, 0.09727585],
       [0.58342823, 0.41657177],
       [0.80315164, 0.19684836],
       [0.53081533, 0.46918467],
       [0.36590983, 0.63409017],
       [0.67299919, 0.32700081],
       [0.58150885, 0.41849115],
       [0.77004058, 0.22995942],
       [0.95027474, 0.04972526],
       [0.42578817, 0.57421183],
       [0.47795603, 0.52204397],
       [0.74601704, 0.25398296],
       [0.94524047, 0.05475953],
       [0.50727342, 0.49272658],
       [0.9388502 , 0.0611498 ],
       [0.90724421, 0.09275579],
       [0.78959663, 0.21040337],
       [0.57472613, 0.42527387],
       [0.70859295, 0.29140705],
       [0.36193021, 0.63806979],
       [0.721323  , 0.278677  ],
       [0.65273468, 0.34726532],
       [0.15686951, 0.84313049],
       [0.34955627, 0.65044373],
       [0.8884563 , 0.1115437 ],
       [0.74231882, 0.25768118],
       [0.26863211, 0.73136789],
       [0.26367   , 0.73633   ],
       [0.86643489, 0.13356511],
       [0.35360505, 0.64639495],
       [0.95395709, 0.04604291],
       [0.89667792, 0.10332208],
       [0.48519409, 0.51480591],
       [0.81644913, 0.18355087],
       [0.84526539, 0.15473461],
       [0.04652073, 0.95347927],
       [0.79251113, 0.20748887],
       [0.081368  , 0.918632  ],
       [0.99726648, 0.00273352],
       [0.68081563, 0.31918437],
       [0.56160963, 0.43839037],
       [0.6705984 , 0.3294016 ],
       [0.87095481, 0.12904519],
       [0.6128607 , 0.3871393 ],
       [0.27264246, 0.72735754],
       [0.31879548, 0.68120452],
       [0.33266227, 0.66733773],
       [0.7825262 , 0.2174738 ],
       [0.28998325, 0.71001675],
       [0.25737046, 0.74262954],
       [0.15034544, 0.84965456],
       [0.85224752, 0.14775248],
       [0.10019863, 0.89980137],
       [0.92791877, 0.07208123],
       [0.81958495, 0.18041505],
       [0.92910964, 0.07089036],
       [0.65302146, 0.34697854],
       [0.84171102, 0.15828898],
       [0.93921821, 0.06078179],
       [0.08682939, 0.91317061],
       [0.6150125 , 0.3849875 ],
       [0.8413934 , 0.1586066 ],
       [0.92844336, 0.07155664],
       [0.68243515, 0.31756485],
       [0.54445321, 0.45554679],
       [0.61981667, 0.38018333],
       [0.29226573, 0.70773427],
       [0.87524533, 0.12475467],
       [0.89803861, 0.10196139],
       [0.78675592, 0.21324408],
       [0.97952102, 0.02047898],
       [0.52428565, 0.47571435],
       [0.1848681 , 0.8151319 ],
       [0.96533206, 0.03466794],
       [0.55120591, 0.44879409],
       [0.59621264, 0.40378736],
       [0.42532994, 0.57467006],
       [0.99016808, 0.00983192],
       [0.25218141, 0.74781859],
       [0.7194233 , 0.2805767 ],
       [0.20290671, 0.79709329],
       [0.15624693, 0.84375307],
       [0.77820359, 0.22179641],
       [0.05312159, 0.94687841],
       [0.85058797, 0.14941203],
       [0.97556292, 0.02443708],
       [0.68183602, 0.31816398],
       [0.91171176, 0.08828824],
       [0.76595796, 0.23404204],
       [0.53051191, 0.46948809],
       [0.69344989, 0.30655011],
       [0.97662099, 0.02337901],
       [0.55400835, 0.44599165],
       [0.0830508 , 0.9169492 ],
       [0.21705972, 0.78294028],
       [0.53506896, 0.46493104],
       [0.45182237, 0.54817763],
       [0.92497363, 0.07502637],
       [0.48134993, 0.51865007],
       [0.75375716, 0.24624284],
       [0.34370553, 0.65629447],
       [0.07487908, 0.92512092],
       [0.78729283, 0.21270717],
       [0.55472717, 0.44527283],
       [0.87179543, 0.12820457],
       [0.04784691, 0.95215309],
       [0.85762194, 0.14237806],
       [0.5961203 , 0.4038797 ],
       [0.38099486, 0.61900514],
       [0.11836531, 0.88163469],
       [0.71364649, 0.28635351],
       [0.6113899 , 0.3886101 ],
       [0.65870001, 0.34129999],
       [0.08016408, 0.91983592],
       [0.17747174, 0.82252826],
       [0.11117834, 0.88882166],
       [0.69064622, 0.30935378],
       [0.33597975, 0.66402025],
       [0.89806369, 0.10193631],
       [0.37754675, 0.62245325],
       [0.70503505, 0.29496495],
       [0.51509764, 0.48490236],
       [0.47564535, 0.52435465],
       [0.23270974, 0.76729026],
       [0.85305758, 0.14694242],
       [0.273652  , 0.726348  ],
       [0.66881639, 0.33118361],
       [0.81454767, 0.18545233],
       [0.79028227, 0.20971773],
       [0.19468194, 0.80531806],
       [0.72945431, 0.27054569],
       [0.45637326, 0.54362674],
       [0.55288278, 0.44711722],
       [0.80125607, 0.19874393],
       [0.71259198, 0.28740802],
       [0.68479367, 0.31520633],
       [0.86294906, 0.13705094],
       [0.08798242, 0.91201758],
       [0.60289411, 0.39710589],
       [0.65310574, 0.34689426],
       [0.90373648, 0.09626352],
       [0.24283191, 0.75716809],
       [0.36327286, 0.63672714],
       [0.95601112, 0.04398888],
       [0.98019413, 0.01980587],
       [0.11888113, 0.88111887],
       [0.6365946 , 0.3634054 ],
       [0.94470102, 0.05529898],
       [0.88978098, 0.11021902],
       [0.88732175, 0.11267825],
       [0.9146885 , 0.0853115 ],
       [0.77358952, 0.22641048],
       [0.72736751, 0.27263249],
       [0.67455332, 0.32544668],
       [0.08693448, 0.91306552],
       [0.82586733, 0.17413267],
       [0.66686794, 0.33313206],
       [0.54295708, 0.45704292],
       [0.30695847, 0.69304153],
       [0.86080229, 0.13919771],
       [0.47407472, 0.52592528],
       [0.13545951, 0.86454049],
       [0.14780636, 0.85219364],
       [0.29668378, 0.70331622],
       [0.25169984, 0.74830016],
       [0.81365727, 0.18634273],
       [0.84864765, 0.15135235],
       [0.13773141, 0.86226859],
       [0.79835562, 0.20164438],
       [0.82038414, 0.17961586],
       [0.22937263, 0.77062737],
       [0.01279221, 0.98720779],
       [0.63876311, 0.36123689],
       [0.09836633, 0.90163367],
       [0.62122629, 0.37877371],
       [0.6049986 , 0.3950014 ],
       [0.61075899, 0.38924101],
       [0.61549512, 0.38450488],
       [0.31627378, 0.68372622],
       [0.34563333, 0.65436667],
       [0.29363402, 0.70636598],
       [0.71520305, 0.28479695],
       [0.87474585, 0.12525415],
       [0.21798176, 0.78201824],
       [0.08829881, 0.91170119],
       [0.62568704, 0.37431296],
       [0.55461322, 0.44538678],
       [0.6962917 , 0.3037083 ],
       [0.79284249, 0.20715751],
       [0.09234587, 0.90765413],
       [0.47892586, 0.52107414],
       [0.72445664, 0.27554336],
       [0.46603051, 0.53396949],
       [0.82832006, 0.17167994],
       [0.63205332, 0.36794668],
       [0.80175443, 0.19824557],
       [0.90327053, 0.09672947],
       [0.23702111, 0.76297889],
       [0.65201474, 0.34798526],
       [0.74040829, 0.25959171],
       [0.82471498, 0.17528502],
       [0.71828955, 0.28171045],
       [0.03481227, 0.96518773],
       [0.79591805, 0.20408195],
       [0.85373079, 0.14626921],
       [0.5797557 , 0.4202443 ],
       [0.5529761 , 0.4470239 ],
       [0.955071  , 0.044929  ],
       [0.82791657, 0.17208343],
       [0.77054168, 0.22945832],
       [0.08944625, 0.91055375],
       [0.26159279, 0.73840721],
       [0.37146006, 0.62853994],
       [0.45621684, 0.54378316],
       [0.27181613, 0.72818387],
       [0.29607189, 0.70392811],
       [0.37654812, 0.62345188],
       [0.58231022, 0.41768978],
       [0.6615789 , 0.3384211 ],
       [0.64422718, 0.35577282],
       [0.58880035, 0.41119965],
       [0.8545084 , 0.1454916 ],
       [0.69231471, 0.30768529],
       [0.22835867, 0.77164133],
       [0.67717212, 0.32282788],
       [0.24894907, 0.75105093],
       [0.22923223, 0.77076777],
       [0.15306602, 0.84693398],
       [0.73621432, 0.26378568],
       [0.80479795, 0.19520205],
       [0.3370318 , 0.6629682 ],
       [0.80145178, 0.19854822],
       [0.89010395, 0.10989605],
       [0.32382371, 0.67617629],
       [0.99285799, 0.00714201],
       [0.61953251, 0.38046749],
       [0.68300038, 0.31699962],
       [0.54355641, 0.45644359],
       [0.56575035, 0.43424965],
       [0.38231302, 0.61768698],
       [0.20482269, 0.79517731],
       [0.96354224, 0.03645776],
       [0.12093019, 0.87906981],
       [0.32832649, 0.67167351],
       [0.58030106, 0.41969894],
       [0.43977075, 0.56022925],
       [0.44333232, 0.55666768],
       [0.82354804, 0.17645196],
       [0.56480851, 0.43519149],
       [0.85845977, 0.14154023],
       [0.74588625, 0.25411375],
       [0.28721422, 0.71278578],
       [0.81133186, 0.18866814],
       [0.86977351, 0.13022649],
       [0.10791828, 0.89208172],
       [0.16326737, 0.83673263],
       [0.93145385, 0.06854615],
       [0.68371837, 0.31628163],
       [0.55080943, 0.44919057],
       [0.62070968, 0.37929032],
       [0.83219132, 0.16780868],
       [0.81449414, 0.18550586],
       [0.87116765, 0.12883235],
       [0.0782498 , 0.9217502 ],
       [0.58762648, 0.41237352],
       [0.38837013, 0.61162987],
       [0.30804273, 0.69195727],
       [0.7115854 , 0.2884146 ],
       [0.38952285, 0.61047715],
       [0.49994995, 0.50005005],
       [0.91326457, 0.08673543],
       [0.92276022, 0.07723978],
       [0.47666777, 0.52333223],
       [0.41088321, 0.58911679],
       [0.79838856, 0.20161144],
       [0.12766834, 0.87233166],
       [0.21802276, 0.78197724],
       [0.518264  , 0.481736  ],
       [0.81295056, 0.18704944],
       [0.08367992, 0.91632008],
       [0.62880516, 0.37119484],
       [0.86501897, 0.13498103],
       [0.74638266, 0.25361734],
       [0.258317  , 0.741683  ],
       [0.17525063, 0.82474937],
       [0.16448959, 0.83551041],
       [0.1213831 , 0.8786169 ],
       [0.37178389, 0.62821611],
       [0.39735944, 0.60264056],
       [0.80250308, 0.19749692],
       [0.98934589, 0.01065411],
       [0.21534051, 0.78465949],
       [0.73911524, 0.26088476],
       [0.90295547, 0.09704453],
       [0.65038169, 0.34961831],
       [0.04781625, 0.95218375],
       [0.99627422, 0.00372578],
       [0.97380292, 0.02619708],
       [0.50601526, 0.49398474],
       [0.80145326, 0.19854674],
       [0.96729446, 0.03270554],
       [0.54676773, 0.45323227],
       [0.41733737, 0.58266263],
       [0.70306485, 0.29693515],
       [0.95977657, 0.04022343],
       [0.95142926, 0.04857074],
       [0.27037632, 0.72962368],
       [0.72828275, 0.27171725],
       [0.73553413, 0.26446587],
       [0.37436291, 0.62563709],
       [0.85071777, 0.14928223],
       [0.72160761, 0.27839239],
       [0.81969255, 0.18030745],
       [0.58825916, 0.41174084],
       [0.98998375, 0.01001625],
       [0.17325423, 0.82674577],
       [0.46145552, 0.53854448],
       [0.76429881, 0.23570119],
       [0.86362512, 0.13637488],
       [0.63547097, 0.36452903],
       [0.31865428, 0.68134572],
       [0.83552335, 0.16447665],
       [0.38594871, 0.61405129],
       [0.23857656, 0.76142344],
       [0.93990091, 0.06009909],
       [0.70343243, 0.29656757],
       [0.81243781, 0.18756219],
       [0.56498034, 0.43501966],
       [0.78139105, 0.21860895],
       [0.6963082 , 0.3036918 ],
       [0.42292566, 0.57707434],
       [0.6923602 , 0.3076398 ],
       [0.9280967 , 0.0719033 ],
       [0.67431643, 0.32568357],
       [0.97331512, 0.02668488],
       [0.45515045, 0.54484955],
       [0.94058715, 0.05941285],
       [0.94207712, 0.05792288],
       [0.74817108, 0.25182892],
       [0.32278389, 0.67721611],
       [0.63764058, 0.36235942],
       [0.75340288, 0.24659712],
       [0.98810976, 0.01189024],
       [0.51916832, 0.48083168],
       [0.91178213, 0.08821787],
       [0.83107643, 0.16892357],
       [0.54906938, 0.45093062],
       [0.54402329, 0.45597671],
       [0.70421071, 0.29578929],
       [0.86760149, 0.13239851],
       [0.73430167, 0.26569833],
       [0.05036563, 0.94963437],
       [0.25522007, 0.74477993],
       [0.2711452 , 0.7288548 ],
       [0.97137593, 0.02862407],
       [0.09222462, 0.90777538],
       [0.39855735, 0.60144265],
       [0.11975568, 0.88024432],
       [0.62818331, 0.37181669],
       [0.80926485, 0.19073515],
       [0.84372169, 0.15627831],
       [0.06158674, 0.93841326],
       [0.20859166, 0.79140834],
       [0.16052301, 0.83947699],
       [0.43677365, 0.56322635],
       [0.08299719, 0.91700281],
       [0.60683719, 0.39316281],
       [0.60089207, 0.39910793],
       [0.82940204, 0.17059796]])

In [228]:
a = np.arange(1,471)

In [229]:
list_of_tuples = list(zip(a, ypred[:,1]))

In [230]:
ss = pd.DataFrame(list_of_tuples, columns=['Id', 'Attrition'])

In [231]:
ss

      Id  Attrition
0      1        0.0
1      2        0.0
2      3        0.0
3      4        0.0
4      5        0.0
5      6        0.0
6      7        0.0
7      8        0.0
8      9        0.0
9     10        0.0
10    11        0.0
11    12        0.0
12    13        0.0
13    14        0.0
14    15        0.0
15    16        0.0
16    17        0.0
17    18        0.0
18    19        0.0
19    20        0.0
20    21        0.0
21    22        0.0
22    23        0.0
23    24        0.0
24    25        0.0
25    26        0.0
26    27        0.0
27    28        0.0
28    29        0.0
29    30        0.0
..   ...        ...
440  441        0.0
441  442        0.0
442  443        0.0
443  444        0.0
444  445        0.0
445  446        0.0
446  447        0.0
447  448        0.0
448  449        0.0
449  450        0.0
450  451        0.0
451  452        0.0
452  453        0.0
453  454        0.0
454  455        0.0
455  456        0.0
456  457        0.0
457  458        0.0
458  459        0.0
459  460        0.0
460  461        0.0
461  462        0.0
462  463        0.0
463  464        0.0
464  465        0.0
465  466        0.0
466  467        0.0
467  468        0.0
468  469        0.0
469  470        0.0

[470 rows x 2 columns]

In [177]:
ss.to_csv('Submission15.csv', index=False)